variables:
  DOCKER_TLS_CERTDIR: "/certs"
  NODE_OPTIONS: '--max_old_space_size=4072'

image: node:14.15-stretch

cache: &global_cache
  key:
    files:
      - yarn.lock
  paths:
    - node_modules/
    - .yarn
  policy: pull

stages:
  - install
  - build
  - publish

install:
  tags:
    - runner2
  stage: install
  before_script:
    - npm set registry https://npm.dev.experium.net
    - npm set //npm.dev.experium.net/:_authToken $NPM_TOKEN
  script:
    - yarn install --frozen-lockfile
  cache:
    <<: *global_cache
    policy: pull-push

build:
  tags:
    - runner2
  stage: build
  script:
    - yarn package
  artifacts:
    paths:
      - lib/

publish:
  tags:
    - runner2
  stage: publish
  before_script:
    - git config user.email "webdev@experium.ru"
    - git config user.name "Experium"
    - npm set //registry.npmjs.org/:_authToken $NPM_API_TOKEN
  script:
    - npm version 1.3.$CI_PIPELINE_IID && npm publish
  dependencies:
    - build
  only:
    - master
