dist: trusty
language: node_js
node_js: lts/*

script:
- echo "skipping tests"

jobs:
  include:
    - stage: npm release
      node_js: lts/*
      before_deploy:
      - yarn install
      - yarn package
      deploy:
        skip_cleanup: true
        edge: true
        provider: script
        script: "cp .npmrc.template $HOME/.npmrc && npm version 1.1.$TRAVIS_BUILD_NUMBER && npm publish"
        on:
          branch: master
    - stage: deploy gh pages
      before_deploy:
      - yarn install
      - yarn build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: "$GITHUB_TOKEN"
        keep-history: true
        local-dir: dist
        on:
          branch: master
